version: "3.8"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo-vol
    restart: unless-stopped
    ports:
      - '27017:27017'
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_password
      - MONGO_INITDB_DATABASE=admin
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=secret
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tuiservice:latest
    container_name: web-vol
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8081:8080"
    expose:
      - 8080
    environment:
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=root_user
      - SPRING_DATA_MONGODB_PASSWORD=root_password
      - SPRING_DATA_MONGODB_DATABASE=mongotui

